spring:
  application:
    name: gamehub
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xmgame
    username: root
    password: 123456
  session:
    timeout: 1478400 # 默认14天
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      add-mappings: false
  mail:
    host: smtp.qq.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: 465
    default-encoding: UTF-8
    protocol: smtps
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 10000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

logging: 
  charset: 
    file: UTF-8
    console: UTF-8

server:
  port: 8080
  servlet:
    context-path: /api

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: userIsDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
  configuration:
    map-underscore-to-camel-case: false

aliyun:
  oss:
    domain: https://xmgame-bucket.oss-cn-guangzhou.aliyuncs.com/
    endpoint: oss-cn-guangzhou.aliyuncs.com
    bucketName: xmgame-bucket

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.xm.gamehub.controller
