spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:test-db}:${MYSQL_PORT:3306}/${MYSQL_DB:xmgame_test}
    username: ${MYSQL_USERNAME:test_user}
    password: ${MYSQL_PASSWORD:test_password}
  session:
    store-type: redis # 指定使用Redis存储Session
    timeout: 1478400 # 默认14天
    redis:
      namespace: game9:sessions:test # Session的Redis命名空间
  mail:
    host: smtp.qq.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT:465}
    default-encoding: UTF-8
    protocol: smtps
  data:
    redis:
      host: ${REDIS_HOST:test-redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      database: 1
      timeout: 10000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

logging:
  level:
    root: INFO
    com.xm.game9: DEBUG
  charset:
    file: UTF-8
    console: UTF-8

server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: /api

# 文件上传配置
file:
  upload-dir: /data/test/uploads/

# API文档配置
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

# 存储配置
storage:
  type: local
  local:
    base-path: /data/test/uploads/

cloudflare:
  r2:
    domain: ${CLOUDFLARE_R2_DOMAIN}
    endpoint: ${CLOUDFLARE_R2_ENDPOINT}
    bucketName: ${CLOUDFLARE_R2_BUCKET}
    accessKeyId: ${CLOUDFLARE_R2_ACCESS_KEY_ID}
    accessKeySecret: ${CLOUDFLARE_R2_ACCESS_KEY_SECRET} 