spring:
  application:
    name: xmgame
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xmgame
    username: root
    password: 123456
  session:
    timeout: 1478400 # 默认14天
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      add-mappings: false
  mail:
    host: smtp.qq.com
    username: noneedtofan@qq.com
    password: "ztatcjfydfgceadh"
    port: 465
    default-encoding: UTF-8
    protocol: smtps
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080
  servlet:
    context-path: /api

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: userIsDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
  configuration:
    map-underscore-to-camel-case: false
