spring:
  application:
    name: game9
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  session:
    timeout: 1478400 # 默认14天
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      add-mappings: false
  mail:
    host: smtp.qq.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT:465}
    default-encoding: UTF-8
    protocol: smtps
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      database: 0
      timeout: 10000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

logging:
  level:
    root: WARN
    com.xm.game9: INFO
  charset:
    file: UTF-8
    console: UTF-8

server:
  address: 0.0.0.0
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: userIsDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: false

# 文件上传配置
file:
  upload-dir: /data/uploads/
  allowed-types: image/jpeg,image/png,image/gif
  max-size: 2097152

# API文档配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: false  # 生产环境禁用Swagger
  api-docs:
    path: /v3/api-docs
    enabled: false  # 生产环境禁用API文档
  packages-to-scan: com.xm.game9.controller

# 存储配置
cloudflare:
  r2:
    domain: ${CLOUDFLARE_R2_DOMAIN}
    endpoint: ${CLOUDFLARE_R2_ENDPOINT}
    bucketName: ${CLOUDFLARE_R2_BUCKET}
    accessKeyId: ${CLOUDFLARE_R2_ACCESS_KEY_ID}
    accessKeySecret: ${CLOUDFLARE_R2_ACCESS_KEY_SECRET}