CREATE TABLE `news`  (
  `newsId` bigint NOT NULL AUTO_INCREMENT COMMENT '资讯ID',
  `newsTitle` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '资讯标题',
  `newsContent` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '资讯内容',
  `newsAuthorId` bigint NOT NULL COMMENT '作者ID (关联用户表)',
  `newsStatus` int NULL DEFAULT 0 COMMENT '资讯状态（0-草稿，1-已发布）',
  `newsCreateTime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `newsUpdateTime` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `newsPublishTime` datetime NULL DEFAULT NULL COMMENT '发布时间',
  `newsIsDelete` int NULL DEFAULT 0 COMMENT '是否删除 (0-未删除, 1-已删除)',
  `newsCoverImage` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '资讯封面图 URL',
  `newsSummary` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '资讯摘要',
  `newsViews` int NULL DEFAULT 0 COMMENT '浏览次数',
  `newsGameTag` bigint NULL DEFAULT NULL COMMENT '游戏标签ID (关联游戏表)',
  `newsGameTagName` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '游戏标签名称',
  `newsCustomTags` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '自定义标签（JSON格式存储多个标签，如：[\"#人工智能\", \"#Java\"]',
  PRIMARY KEY (`newsId`) USING BTREE,
  INDEX `idx_news_author_id`(`newsAuthorId`) USING BTREE,
  INDEX `idx_news_status`(`newsStatus`) USING BTREE,
  INDEX `idx_news_publish_time`(`newsPublishTime`) USING BTREE,
  INDEX `idx_news_game_tag`(`newsGameTag`) USING BTREE,
  INDEX `idx_news_game_tag_name`(`newsGameTagName`) USING BTREE,
  INDEX `idx_news_custom_tags`(`newsCustomTags`(255)) USING BTREE,
  CONSTRAINT `fk_news_author` FOREIGN KEY (`newsAuthorId`) REFERENCES `user` (`userId`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 17 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '资讯表' ROW_FORMAT = Dynamic;
